# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Ingredient.create(name: "lemon")
Ingredient.create(name: "ice")
Ingredient.create(name: "mint leaves")
Ingredient.create(name: "bourbon")
Ingredient.create(name: "rye whiskey")
Ingredient.create(name: "sugar")
Ingredient.create(name: "Angostura bitters")
Ingredient.create(name: "Fee Brothers’ Whiskey Barrel")
Ingredient.create(name: "Old Tom gin")
Ingredient.create(name: "Vermouth")
Ingredient.create(name: "maraschino liqueur")
Ingredient.create(name: "orange bitters")
Ingredient.create(name: "dry gin")
Ingredient.create(name: "Maraschino cherries")
Ingredient.create(name: "Amer Picon")
Ingredient.create(name: "light rum")
Ingredient.create(name: "dark rum")
Ingredient.create(name: "fresh lime juice")
Ingredient.create(name: "lime wheels")
Ingredient.create(name: "coarse salt")
Ingredient.create(name: "tequila")
Ingredient.create(name: "Cointreau")
Ingredient.create(name: "Cognac")
Ingredient.create(name: "Armagnac")
Ingredient.create(name: "lemon juice")
Ingredient.create(name: "Champagne")
Ingredient.create(name: "cocktail cherry")
Ingredient.create(name: "celery salt")
Ingredient.create(name: "Worcestershire sauce")
Ingredient.create(name: "soy sauce")
Ingredient.create(name: "black pepper")
Ingredient.create(name: "cayenne pepper")
Ingredient.create(name: "hot sauce")
Ingredient.create(name: "horseradish")
Ingredient.create(name: "vodka")
Ingredient.create(name: "tomato juice")
Ingredient.create(name: "celery stick")
Ingredient.create(name: "Laird's Applejack")
Ingredient.create(name: "grenadine")
Ingredient.create(name: "Peychaud's bitters")
Ingredient.create(name: "Campari")
Ingredient.create(name: "water")
Ingredient.create(name: "Herbsaint")
Ingredient.create(name: "Pernod")
Ingredient.create(name: "pastis")
Ingredient.create(name: "absinthe")
Ingredient.create(name: "Benedictine")
Ingredient.create(name: "cream")
Ingredient.create(name: "egg white")
Ingredient.create(name: "orange flower water")
Ingredient.create(name: "Seltzer")
Ingredient.create(name: "Mint sprigs")
Ingredient.create(name: "Crushed ice")
Ingredient.create(name: "St. James 15-year Hors D’Age rum")
Ingredient.create(name: "Appleton Extra rum")
Ingredient.create(name: "curaçao")
Ingredient.create(name: "orgeat")
Ingredient.create(name: "rock-candy syrup")
Ingredient.create(name: "vanilla extract")
Ingredient.create(name: "Coruba dark Jamaican rum")
Ingredient.create(name: "simple syrup")
Ingredient.create(name: "cranberry juice")
Ingredient.create(name: "pisco")
Ingredient.create(name: "Amargo bitters")
Ingredient.create(name: "club soda")
Ingredient.create(name: "Chartreuse (green)")
Cocktail.create(name: "Old Fashioned")
Cocktail.create(name: "Martinez")
Cocktail.create(name: "Martini")
Cocktail.create(name: "Manhattan")
Cocktail.create(name: "Brooklyn")
Cocktail.create(name: "Daiquiri")
Cocktail.create(name: "Margarita")
Cocktail.create(name: "Sidecar")
Cocktail.create(name: "French 75")
Cocktail.create(name: "Bloody Mary")
Cocktail.create(name: "Jack Rose")
Cocktail.create(name: "Negroni")
Cocktail.create(name: "Boulevardier")
Cocktail.create(name: "Sazerac")
Cocktail.create(name: "Vieux Carré")
Cocktail.create(name: "Ramos Gin Fizz")
Cocktail.create(name: "Mint Julep")
Cocktail.create(name: "Whiskey Sour")
Cocktail.create(name: "Mai Tai")
Cocktail.create(name: "Planter's Punch")
Cocktail.create(name: "Pisco Sour")
Cocktail.create(name: "Cosmopolitan")
Cocktail.create(name: "Tom Collins")
Cocktail.create(name: "Last Word")
Cocktail.create(name: "Cosmopolitan")
